name: Builder
on: [push, pull_request]
jobs:
  macos:
    name: ${{ matrix.name }}
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        name: [macOS, macOS(SwiftPM)]
        include:
          - name: macOS
            use_xcodebuild: true
            sdk: macosx
            destination: 'platform=macOS'
          - name: macOS(SwiftPM)
            use_xcodebuild: false
    env:
      use_xcodebuild: ${{ matrix.use_xcodebuild }}
      schemes: DBBrowser
      sdk: ${{ matrix.sdk }}
      destination: ${{ matrix.destination }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
  ubuntu_swift:
    name: ${{ matrix.swift_version }}-${{ matrix.distro }}
    container: 
      image: docker://swift:${{ matrix.swift_version }}-${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift_version: [5.3, 5.4]
        distro: [bionic, focal]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare		
      run: apt-get update
    - name: Install libmongoc
      run: apt-get install -y libmongoc-1.0-0 libssl-dev
    - name: Install JavaScriptCore
      run: apt-get install -y libjavascriptcoregtk-4.0-dev
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
  linux_swift:
    name: ${{ matrix.swift_version }}-${{ matrix.distro }}
    container:
      image: docker://swift:${{ matrix.swift_version }}-${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift_version: [5.3, 5.4]
        distro: [centos8]
        include:
          - distro: centos8
            jsc: webkit2gtk3-jsc-devel
            allowerasing: --allowerasing
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare		
      run: yum update -y ${{ matrix.allowerasing }} && yum install -y libstdc++-devel
    - name: Install libmongoc
      run: yum install -y mongo-c-driver openssl-devel
    - name: Install JavaScriptCore
      run: yum install -y ${{ matrix.jsc }}
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
  ubuntu_swift_nightly:
    name: nightly-${{ matrix.swift_version }}-${{ matrix.distro }}
    container:
      image: docker://swiftlang/swift:nightly-${{ matrix.swift_version }}-${{ matrix.distro }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        swift_version: [5.5, main]
        distro: [bionic, focal]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare		
      run: apt-get update
    - name: Install libmongoc
      run: apt-get install -y libmongoc-1.0-0 libssl-dev
    - name: Install JavaScriptCore
      run: apt-get install -y libjavascriptcoregtk-4.0-dev
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
  linux_swift_nightly:
    name: nightly-${{ matrix.swift_version }}-${{ matrix.distro }}
    container:
      image: docker://swiftlang/swift:nightly-${{ matrix.swift_version }}-${{ matrix.distro }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        swift_version: [5.5, main]
        distro: [centos8]
        include:
          - distro: centos8
            jsc: webkit2gtk3-jsc-devel
            allowerasing: --allowerasing
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare		
      run: yum update -y ${{ matrix.allowerasing }}
    - name: Install libmongoc
      run: yum install -y mongo-c-driver openssl-devel
    - name: Install JavaScriptCore
      run: yum install -y ${{ matrix.jsc }}
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
